### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: 获取目录树失败

### ISSUE THREAD

**Issue by JiehuiSun** [yuque-helper/yuque2book#10]
(node:28338) UnhandledPromiseRejectionWarning: Error: 获取目录树失败
    at Object.<anonymous> (/usr/local/lib/node_modules/yuque2book/dist/src/lib/index.js:143:23)
    at step (/usr/local/lib/node_modules/yuque2book/dist/src/lib/index.js:32:23)
    at Object.throw (/usr/local/lib/node_modules/yuque2book/dist/src/lib/index.js:13:53)
    at rejected (/usr/local/lib/node_modules/yuque2book/dist/src/lib/index.js:5:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:28338) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:28338) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

请问这是怎么回事呀？

**Comment by cctv1005s** [comment]
你的文档能分享给我看一下吗？
