### ISSUE TITLE
用大佬的工具导出后运行报错

### ISSUE THREAD

**Issue by ddy4633** [yuque-helper/yuque2book#15]
(mypy3) ➜  /yuque anywhere 
_tls_common.js:135
      c.context.setCert(cert);
                ^

Error: error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small
    at Object.createSecureContext (_tls_common.js:135:17)
    at Server (_tls_wrap.js:873:27)
    at new Server (https.js:62:14)
    at Object.createServer (https.js:85:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/anywhere/bin/anywhere:131:7)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by cctv1005s** [comment]
anywhere 用不了的话话，可以试试别的工具，比如说 `python -m SimpleHTTPServer 8099`
