### ISSUE TITLE
[功能请求]支持导出密码保护的文档

### ISSUE THREAD

**Issue by brace-great** [yuque-helper/yuque2book#35]
导出需要输入密码的文档会直接报错
<ref *4> Error: Not Found
    at Request.callback (D:\.mf\mpj\yuque2book\node_modules\superagent\lib\node\index.js:804:15)
    at D:\.mf\mpj\yuque2book\node_modules\superagent\lib\node\index.js:1036:18
    at IncomingMessage.<anonymous> (D:\.mf\mpj\yuque2book\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  status: 404,
......

**Comment by cctv1005s** [comment]
😅 让我试试，可能不一定行

**Comment by cctv1005s** [comment]
不行，之前尝试了一段时间，这个 api 目前不被语雀支持
